### ISSUE TITLE
Questions about the loss function used by the RAW2RGB network

### ISSUE THREAD

**Issue by lisen0** [swz30/CycleISP#1]
Hello,
I am wondering why not use the log loss term in the RAW2RGB network, just like in the RGB2RAW network. Are there any principles? Or is it just set empirically?

**Comment by swz30** [comment]
Hi, 

RAW images tend to have a lot of dark values (therefore, have a skewed histogram towards dark side). "_The log loss term is added to enforce approximately equal treatment for all the image values; otherwise the network dedicates more attention to recovering the highlight regions (from where it receives larger gradients)._" This is not the case for the sRGB images. 

Well exposed sRGB images have uniform histograms (mean pixel value around 0.5). Therefore, there is not a need for the log loss term for the RAW2RGB network.

**Comment by lisen0** [comment]
OK, I get it. Thanks very much.
